#!/bin/sh
### BEGIN INIT INFO
# Provides:       cpugpufreqboost
# Required-Start: $remote_fs cpufrequtils
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description: Enable CPU boost and set max GPU clock
# Description: Enable CPU boost and set max GPU clock
### END INIT INFO
# 

DESC="CPU/GPU Frequency Boost"

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# use lsb-base
. /lib/lsb/init-functions


case "$1" in
	start|force-reload|restart|reload)
		log_action_begin_msg "$DESC: Setting CPU Boost to 1 (enabled)"
                echo 1 > /sys/devices/system/cpu/cpufreq/boost

                GPU_CLOCK=$(cat /sys/class/misc/mali0/device/devfreq/devfreq0/available_frequencies | tr " " "\n" | sort -n | tail -n1)
                log_action_cont_msg "$DESC: Setting GPU Clock to $GPU_CLOCK"

                echo "userspace" > /sys/class/misc/mali0/device/devfreq/devfreq0/governor
                echo $GPU_CLOCK > /sys/class/misc/mali0/device/devfreq/devfreq0/min_freq
                echo $GPU_CLOCK > /sys/class/misc/mali0/device/devfreq/devfreq0/max_freq

                log_action_end_msg 0
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}"
		exit 1
esac

exit 0
