diff --git a/shell/linux/Makefile b/shell/linux/Makefile
index aac6efb4..724923f9 100644
--- a/shell/linux/Makefile
+++ b/shell/linux/Makefile
@@ -127,6 +127,14 @@ else ifneq (,$(findstring armv7h,$(platform)))
     CFLAGS += -D TARGET_BEAGLE -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant
     USE_GLES := 1
 
+# Tinker Board KMS
+else ifneq (,$(findstring tinkerkms,$(platform)))
+    MFLAGS:=
+    ASFLAGS:=-mfloat-abi=hard -march=armv7-a -O2 -marm -march=armv7-a -mtune=cortex-a17 -mfpu=neon-vfpv4 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -DGL_GLEXT_PROTOTYPES -pipe -D TARGET_BEAGLE -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize
+    CFLAGS:=-mfloat-abi=hard -march=armv7-a -O2 -marm -march=armv7-a -mtune=cortex-a17 -mfpu=neon-vfpv4 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -DGL_GLEXT_PROTOTYPES -pipe -D TARGET_BEAGLE -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize
+    USE_GLES := 1
+    USE_SDL := 1
+
 # LinCPP
 else ifneq (,$(findstring lincpp,$(platform)))
     CPP_REC := 1
